### PR TITLE
Support building using specific symfony version

### PR DESCRIPTION
**Pull request by kejwmen**
Hi,
I've seen a question about installing specific symfony version on symfony slack and thought it could be supported here.

Not sure about `VERSION` default value in compose, but we'll probably figure it out.

What do you think?

### CODE REVIEW

**Comment by dunglas** [comment]
`VERSION` must also be used here: https://github.com/dunglas/symfony-docker/blob/master/docker/app/docker-entrypoint.sh#L12

/cc @reypm

**Comment by dunglas** [comment]
ping @kejwmen, do you want me to finish this one?

**Comment by reypm** [comment]
@dunglas I am not the owner of this but yeah it would be great if you finish this and add it to the stack 💯

**Comment by kejwmen** [comment]
Sorry, I forgot about this PR and thought there was a similiar one, already merged.

I will finish it later today.

**Comment by kejwmen** [comment]
Done, sorry for delay ;)

**Comment by kejwmen** [comment]
should we add a README to document this behavior?

**Comment by dunglas** [comment]
Yes it would be awesome to add a README.

**Comment by dunglas** [comment]
Thanks!

**Pull request merged**
