### PR TITLE
fix: php ini loading order

### PR DESCRIPTION
**Pull request by wizhippo**
https://github.com/dunglas/symfony-docker/issues/538

As php takes the last ini value set, in frankenphp/conf.d

The order currently is:

app.dev.ini
app.ini

Expected would be:

app.ini
app.dev.ini

This renames app.dev.ini to app.zzz-dev.ini so it is loaded last.

### CODE REVIEW

**Comment by wizhippo** [comment]
Perhaps need to be changed again so both app.ini and app.dev.ini are both loaded after all others?

app.ini ->  zzz-app.ini
add.dev.ini -> zzz-dev.ini

**Comment by dunglas** [comment]
Maybe 01- and 02- ?

**Comment by wizhippo** [comment]
> #538

I commented in the issue but wont leading with numbers load before any docker-php-ext-xyz.ini configs?  Normally do we not want app to supersede those too?  That's why I choose the zzz prefix.  Also in the case of zzz-dev.ini, that seems more likely to be always last. even if adding other user config files.

**Comment by maxhelias** [comment]
Yes, you're right. So we need something that passes after `docker-php-ext`.
What do you think about renaming `app` in `php` in this case for files to come after extensions and then choosing how to put the dev last?

**Comment by leroy0211** [comment]
I've opened another PR #617 based on my comment in #538.

**Pull request closed without merging**
