### PR TITLE
correct wrongly typed docker-compose

### PR DESCRIPTION
**Pull request by fullbl**
There is an error in documentation, docker-compose is a unique command!

### CODE REVIEW

**Comment by jdreesen** [comment]
Nope, that's the legacy docker compose V1. Docker compose V2 is `docker compose` instead of `docker-compose`, so the docs are correct.

**Comment by senzowayne** [comment]
J'ai fais l'installation sur un ubuntu dernière version et c'est bien `docker compose` et plus `docker-compose`

**Comment by fullbl** [comment]
My bad, I thought it was a typo. Thank you for the information, didn't know about it (https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command)!

**Comment by maxhelias** [comment]
This is the new command with the space, see : https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command

**Pull request closed without merging**
