### PR TITLE
docs(production): fix command to run containers

### PR DESCRIPTION
**Pull request by drazik**
The commands were pointing to a `docker-compose.yml` file that doesn't exist. It's `compose.yaml` now.

### CODE REVIEW

**Comment by maxhelias** [comment]
In `docs/production.md` too

**Comment by drazik** [comment]
Should be good now

**Comment by stefantalen** [comment]
Thanks! This will fix #510

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
Thanks!

**Pull request merged**
