### PR TITLE
Add link to Laravel Docker.

### PR DESCRIPTION
**Pull request by FunkyOz**

### CODE REVIEW

**Comment by maxhelias** [comment]
Hi @FunkyOz,

It's very nice what you do for Laravel based on this one. I very like it
Before I decide, I'd like to try it and give some time to have some feedback.

Thanks for your understanding.

**Comment by FunkyOz** [comment]
Yes, sure not problems, thank you

**Comment by dsentker** [comment]
There are a handful of good PHP frameworks, I don't think a specific framework needs its own readme section linking to other projects.

**Comment by maxhelias** [comment]
Hi,
I do agree with @dsentker.. 
What's more, frankenphp offers integration compatible with Octane: https://frankenphp.dev/docs/laravel/
Thank you for backporting this project as it is for Laravel.

**Comment by maxhelias** [comment]
@FunkyOz For your information : https://x.com/maxhelias/status/1832714849639428274 😉

**Pull request closed without merging**
