### PR TITLE
Rename docker-compose*.yml docker-compose*.yaml

### PR DESCRIPTION
**Pull request by lyrixx**
In order to ease `bin/console make:docker:database` because it uses `.yaml` file

### CODE REVIEW

**Review by maxhelias — APPROVED** [review]

**Comment by dunglas** [comment]
I would prefer to keep it as is. In their docs Docker Compose uses `.yml` and it's also the most used extension in various docs and tools.

**Comment by DuboisS** [comment]
Yes, rename it directly in maker-bundle.

**Comment by weaverryan** [comment]
We can (should) also make MakerBundle aware of both formats - have it look for both. That should be an easy, ideal solution I think.

**Comment by dunglas** [comment]
Closing as this will handled directly in MakerBundle.

**Pull request closed without merging**
