### PR TITLE
Removing the warning for the PHP Intl extension

### PR DESCRIPTION
**Pull request by jevillard**
**My docker + docker-compose version**
* _docker version 18.09.3, build 774a1f4_
* _docker-compose version 1.23.1, build b02f1306_

**Steps to reproduce:**
* `git clone https://github.com/dunglas/symfony-docker.git`
* `cd symfony-docker`
* `docker-compose up`

**Result**  
```
Creating symfony-docker_app_1_3a027395d299 ... done
Creating symfony-docker_nginx_1_563b5da73158 ... done
Creating symfony-docker_h2-proxy_1_8fcfd6bfc42c ... done
Attaching to symfony-docker_app_1_2e2dbf6f980b, symfony-docker_nginx_1_d7979f7f7b06, symfony-docker_h2-proxy_1_7de1995111d1
app_1_2e2dbf6f980b | PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so (Error loading shared library libicui18n.so.62: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so.so: No such file or directory)) in Unknown on line 0
```

### CODE REVIEW

**Comment by maxhelias** [comment]
I can not reproduce your warning, i'm on mac and with docker-compose version 1.24.0-rc1
Can you give us more details ?

**Comment by jevillard** [comment]
Ok, I attach a screenshot of my terminal with more details, if it can help reproduce the problem  
dunglas-docker

**Comment by DamienHarper** [comment]
@jevillard I fixed this by removing the `--virtual .persistent-deps` in the `Dockerfile` at [line 35](https://github.com/dunglas/symfony-docker/blob/d5cc26520a156731110e5c3cf486d2aa056ff5e9/Dockerfile#L35). I hadn't enough time to investigate so I don't exactly know if this is an alpine issue or not.

**Comment by dunglas** [comment]
I can confirm the issue (on Mac):

```
app_1       | PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so (Error loading shared library libicui18n.so.62: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so.so: No such file or directory)) in Unknown on line 0
app_1       |
app_1       | Warning: PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so (Error loading shared library libicui18n.so.62: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so.so: No such file or directory)) in Unknown on line 0
```

**Comment by dunglas** [comment]
Thanks @jevillard

**Pull request merged**
