### PR TITLE
Use binary-only images for installing Composer

### PR DESCRIPTION
**Pull request by Wirone**
See: https://blog.codito.dev/2022/11/composer-binary-only-docker-images/

### CODE REVIEW

**Comment by mario-fehr** [comment]
Duplicate of #320

**Comment by Wirone** [comment]
@mario-fehr as an author of binary-only images I reserve the right to make this change! 😆

**Comment by maxhelias** [comment]
Sorry, I always apply the first PR policy 😄

**Comment by maxhelias** [comment]
Thanks anyway ;)

**Pull request closed without merging**
